// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOXXtSxcdykzZOylG0aG-rRAIHe6jvYE',
    appId: '1:969764953163:web:bdd21677ba20389ead81ce',
    messagingSenderId: '969764953163',
    projectId: 'harbor-connect-dev',
    authDomain: 'harbor-connect-dev.firebaseapp.com',
    storageBucket: 'harbor-connect-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgaKo7fDwm6v4bMTDDHo6QlB6aJ8jQ8U',
    appId: '1:969764953163:android:c41f6b7bff6a199dad81ce',
    messagingSenderId: '969764953163',
    projectId: 'harbor-connect-dev',
    storageBucket: 'harbor-connect-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv-bWTXS5QR-kiULQSe6X26Jxv4ZN4LT0',
    appId: '1:1003878953130:ios:f2fb03ee31bc53d4e260d3',
    messagingSenderId: '1003878953130',
    projectId: 'harbor-connect-prod',
    storageBucket: 'harbor-connect-prod.firebasestorage.app',
    iosClientId: '1003878953130-pg6g3o22vifmhqgtvhrk05cuh4hp3p8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.lbcHarborConnect',
  );

}